"""Export the reviewed Blender strawberry assets for Gazebo Harmonic.

The exporter intentionally keeps the plant and fruit responsibilities separate:

* the plant owns crown, leaves, petioles, inflorescences, and pedicels;
* a graspable fruit owns body, seeds, and calyx, but not the long display stem.

It writes plain OBJ/MTL files in metres with Blender/Gazebo Z-up coordinates,
plus JSON metadata containing the fruit centre and plant attachment poses.
"""

from __future__ import annotations

import json
import math
import re
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Callable

import bpy
from mathutils import Matrix, Vector


FRUIT_SOURCE_OBJECTS = {
    "calyx_center_v5",
    "calyx_leaf_v5_00",
    "calyx_leaf_v5_01",
    "calyx_leaf_v5_02",
    "calyx_leaf_v5_03",
    "calyx_leaf_v5_04",
    "calyx_leaf_v5_05",
    "calyx_leaf_v5_06",
    "strawberry_ripe_body_v5",
    "strawberry_seeds_v5",
}
FRUIT_BODY_OBJECT = "strawberry_ripe_body_v5"
FRUIT_MOUNT_OBJECT = "calyx_center_v5"
PLANT_ROOT_OBJECT = "strawberry_plant_v2_root"
ATTACHMENT_ROOTS = OrderedDict(
    (
        # Keep the primary control target on the front-left, robot-reachable
        # pedicel. The source scene's back-right ripe fruit remains ID 3.
        ("strawberry_1", ("ripe_fruit_attachment_01_00_root", "RIPE")),
        ("strawberry_2", ("unripe_fruit_attachment_00_01_root", "UNRIPE")),
        ("strawberry_3", ("ripe_fruit_attachment_00_00_root", "RIPE")),
        ("strawberry_4", ("ripe_fruit_attachment_01_01_root", "RIPE")),
    )
)
UNRIPE_COLORS = {
    "Ripe_Strawberry_Red": (0.20, 0.55, 0.055, 1.0),
    "Strawberry_Seed_Yellow": (0.55, 0.66, 0.18, 1.0),
}


def _argv() -> list[str]:
    if "--" not in sys.argv:
        return []
    return sys.argv[sys.argv.index("--") + 1 :]


def _safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")
    return cleaned or "material"


def _bounds(objects: list[bpy.types.Object]) -> tuple[Vector, Vector]:
    lower = Vector((math.inf, math.inf, math.inf))
    upper = Vector((-math.inf, -math.inf, -math.inf))
    found = False
    for obj in objects:
        if not getattr(obj, "bound_box", None):
            continue
        for corner in obj.bound_box:
            point = obj.matrix_world @ Vector(corner)
            for axis in range(3):
                lower[axis] = min(lower[axis], point[axis])
                upper[axis] = max(upper[axis], point[axis])
            found = True
    if not found:
        raise RuntimeError("cannot calculate bounds for an empty object list")
    return lower, upper


def _rgba(material: bpy.types.Material | None) -> tuple[float, float, float, float]:
    if material is None:
        return (0.6, 0.6, 0.6, 1.0)
    color = tuple(float(value) for value in material.diffuse_color)
    if len(color) == 4:
        return color
    return (*color[:3], 1.0)


def _write_mtl(
    path: Path,
    materials: OrderedDict[str, tuple[float, float, float, float]],
) -> None:
    lines = [
        "# Generated from reviewed Blender assets for Strawberry URP.",
        "# Colours are intentionally embedded; the source files use no image textures.",
        "",
    ]
    for name, rgba in materials.items():
        red, green, blue, alpha = rgba
        lines.extend(
            [
                f"newmtl {name}",
                f"Ka {red * 0.35:.6f} {green * 0.35:.6f} {blue * 0.35:.6f}",
                f"Kd {red:.6f} {green:.6f} {blue:.6f}",
                "Ks 0.080000 0.080000 0.080000",
                "Ns 24.000000",
                f"d {alpha:.6f}",
                "illum 2",
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def _write_obj(
    path: Path,
    objects: list[bpy.types.Object],
    *,
    origin: Vector,
    material_overrides: dict[str, tuple[float, float, float, float]] | None = None,
    decimate_ratio: Callable[[bpy.types.Object], float] | None = None,
) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    material_overrides = material_overrides or {}
    material_names: OrderedDict[str, tuple[float, float, float, float]] = OrderedDict()
    object_records = []
    vertex_offset = 0
    normal_offset = 0
    lines = [
        "# Strawberry URP Gazebo mesh generated by export_gazebo_assets.py",
        f"mtllib {path.with_suffix('.mtl').name}",
        "",
    ]
    depsgraph = bpy.context.evaluated_depsgraph_get()

    for obj in sorted(objects, key=lambda item: item.name):
        # Convert every source object to a temporary mesh first. This makes the
        # same deterministic Decimate path work for both meshes and curves
        # without modifying or saving the reviewed Blender source.
        evaluated_source = obj.evaluated_get(depsgraph)
        source_mesh = bpy.data.meshes.new_from_object(
            evaluated_source,
            preserve_all_data_layers=True,
            depsgraph=depsgraph,
        )
        temporary = bpy.data.objects.new(f"__gazebo_export_{obj.name}", source_mesh)
        bpy.context.scene.collection.objects.link(temporary)
        temporary.matrix_world = obj.matrix_world.copy()
        ratio = (
            max(0.01, min(1.0, float(decimate_ratio(obj))))
            if decimate_ratio is not None
            else 1.0
        )
        if ratio < 0.999999:
            modifier = temporary.modifiers.new(
                name="Gazebo visual decimation",
                type="DECIMATE",
            )
            modifier.decimate_type = "COLLAPSE"
            modifier.ratio = ratio
            modifier.use_collapse_triangulate = True
        bpy.context.view_layer.update()
        evaluated = temporary.evaluated_get(depsgraph)
        mesh = evaluated.to_mesh()
        if mesh is None or not mesh.vertices:
            if mesh is not None:
                evaluated.to_mesh_clear()
            bpy.data.objects.remove(temporary, do_unlink=True)
            bpy.data.meshes.remove(source_mesh)
            continue
        mesh.calc_loop_triangles()
        transform = temporary.matrix_world
        normal_transform = transform.to_3x3().inverted_safe().transposed()

        lines.append(f"o {_safe_name(obj.name)}")
        for vertex in mesh.vertices:
            point = transform @ vertex.co - origin
            lines.append(f"v {point.x:.9f} {point.y:.9f} {point.z:.9f}")
        for vertex in mesh.vertices:
            normal = (normal_transform @ vertex.normal).normalized()
            lines.append(f"vn {normal.x:.9f} {normal.y:.9f} {normal.z:.9f}")

        active_material = None
        for triangle in mesh.loop_triangles:
            polygon = mesh.polygons[triangle.polygon_index]
            material = (
                mesh.materials[polygon.material_index]
                if polygon.material_index < len(mesh.materials)
                else None
            )
            source_name = material.name if material else "Default"
            target_name = _safe_name(source_name)
            rgba = material_overrides.get(source_name, _rgba(material))
            material_names.setdefault(target_name, rgba)
            if active_material != target_name:
                lines.append(f"usemtl {target_name}")
                active_material = target_name
            corners = []
            for vertex_index in triangle.vertices:
                obj_index = vertex_offset + int(vertex_index) + 1
                normal_index = normal_offset + int(vertex_index) + 1
                corners.append(f"{obj_index}//{normal_index}")
            lines.append("f " + " ".join(corners))

        object_records.append(
            {
                "name": obj.name,
                "type": obj.type,
                "decimate_ratio": round(ratio, 4),
                "vertices": len(mesh.vertices),
                "triangles": len(mesh.loop_triangles),
            }
        )
        vertex_offset += len(mesh.vertices)
        normal_offset += len(mesh.vertices)
        lines.append("")
        evaluated.to_mesh_clear()
        bpy.data.objects.remove(temporary, do_unlink=True)
        bpy.data.meshes.remove(source_mesh)

    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    _write_mtl(path.with_suffix(".mtl"), material_names)
    return {
        "path": str(path),
        "objects": object_records,
        "vertices": vertex_offset,
        "triangles": sum(record["triangles"] for record in object_records),
        "materials": list(material_names),
    }


def _round_vector(vector: Vector, digits: int = 9) -> list[float]:
    return [round(float(value), digits) for value in vector]


def _round_quaternion(quaternion, digits: int = 9) -> list[float]:
    return [
        round(float(quaternion.x), digits),
        round(float(quaternion.y), digits),
        round(float(quaternion.z), digits),
        round(float(quaternion.w), digits),
    ]


def _round_euler(euler, digits: int = 9) -> list[float]:
    return [round(float(value), digits) for value in euler]


def export_fruit(source: Path, output_root: Path) -> dict:
    bpy.ops.wm.open_mainfile(filepath=str(source))
    missing = sorted(FRUIT_SOURCE_OBJECTS.difference(bpy.data.objects.keys()))
    if missing:
        raise RuntimeError(f"fruit source is missing required objects: {missing}")
    objects = [bpy.data.objects[name] for name in sorted(FRUIT_SOURCE_OBJECTS)]
    body = bpy.data.objects[FRUIT_BODY_OBJECT]
    mount_object = bpy.data.objects[FRUIT_MOUNT_OBJECT]
    body_lower, body_upper = _bounds([body])
    fruit_center = (body_lower + body_upper) * 0.5
    mount_point_source = mount_object.matrix_world.translation.copy()
    mount_point_model = mount_point_source - fruit_center
    visible_lower, visible_upper = _bounds(objects)

    def fruit_decimation(obj: bpy.types.Object) -> float:
        if obj.name == "strawberry_ripe_body_v5":
            return 0.16
        if obj.name.startswith("calyx_leaf_v5_"):
            return 0.30
        if obj.name == "calyx_center_v5":
            return 0.30
        return 1.0

    ripe = _write_obj(
        output_root / "strawberry_ripe" / "meshes" / "strawberry_ripe_visual_v2.obj",
        objects,
        origin=fruit_center,
        decimate_ratio=fruit_decimation,
    )
    unripe = _write_obj(
        output_root
        / "strawberry_unripe"
        / "meshes"
        / "strawberry_unripe_visual_v2.obj",
        objects,
        origin=fruit_center,
        material_overrides=UNRIPE_COLORS,
        decimate_ratio=fruit_decimation,
    )
    return {
        "source": str(source),
        "source_blender_version": bpy.app.version_string,
        "excluded_object": "strawberry_curved_stem_v5",
        "origin_rule": "centre of strawberry_ripe_body_v5 world-space bounds",
        "source_origin_m": _round_vector(fruit_center),
        "mount_rule": "calyx_center_v5 object origin connects directly to the plant pedicel",
        "mount_point_in_model_frame_m": _round_vector(mount_point_model),
        "source_visible_bounds_m": {
            "min": _round_vector(visible_lower),
            "max": _round_vector(visible_upper),
        },
        "exported_bounds_m": {
            "min": _round_vector(visible_lower - fruit_center),
            "max": _round_vector(visible_upper - fruit_center),
        },
        "ripe": ripe,
        "unripe": unripe,
    }


def export_plant(
    source: Path,
    output_root: Path,
    fruit_center: Vector,
    mount_point_model: Vector,
) -> dict:
    bpy.ops.wm.open_mainfile(filepath=str(source))
    root = bpy.data.objects.get(PLANT_ROOT_OBJECT)
    if root is None:
        raise RuntimeError(f"plant source is missing {PLANT_ROOT_OBJECT}")

    # Only direct geometric children belong to the plant shell. Mounted fruits
    # are below attachment empties and imported templates are separate roots.
    objects = [
        obj
        for obj in bpy.data.objects
        if obj.parent == root and obj.type in {"MESH", "CURVE"}
    ]
    if not objects:
        raise RuntimeError("plant source has no direct geometric children")
    lower, upper = _bounds(objects)
    def plant_decimation(obj: bpy.types.Object) -> float:
        if obj.name.endswith("_midrib"):
            return 0.25
        if obj.type == "CURVE":
            return 0.40
        if obj.name.startswith(("leaf_center_", "leaf_left_", "leaf_right_")):
            return 0.45
        if obj.name == "strawberry_crown_v2":
            return 0.50
        return 1.0

    plant = _write_obj(
        output_root / "strawberry_plant_v2" / "meshes" / "strawberry_plant_v2.obj",
        objects,
        origin=Vector((0.0, 0.0, 0.0)),
        decimate_ratio=plant_decimation,
    )

    attachments = []
    for model_name, (root_name, maturity) in ATTACHMENT_ROOTS.items():
        fruit_root = bpy.data.objects.get(root_name)
        if fruit_root is None:
            raise RuntimeError(f"plant source is missing mounted fruit root {root_name}")
        centre_world = fruit_root.matrix_world @ fruit_center
        rotation = fruit_root.matrix_world.to_quaternion().normalized()
        euler = rotation.to_euler("XYZ")
        attachment_point = fruit_root.parent.matrix_world.translation.copy()
        direct_mount_center = attachment_point - rotation @ mount_point_model
        attachments.append(
            {
                "model_name": model_name,
                "source_root": root_name,
                "maturity": maturity,
                "centre_in_plant_frame_m": _round_vector(centre_world),
                "pedicel_endpoint_in_plant_frame_m": _round_vector(attachment_point),
                "direct_mount_center_in_plant_frame_m": _round_vector(
                    direct_mount_center
                ),
                "orientation_xyzw": _round_quaternion(rotation),
                "orientation_rpy_rad": _round_euler(euler),
                "source_uniform_scale": round(
                    sum(float(value) for value in fruit_root.matrix_world.to_scale())
                    / 3.0,
                    6,
                ),
            }
        )

    return {
        "source": str(source),
        "source_blender_version": bpy.app.version_string,
        "selection_rule": (
            "direct MESH/CURVE children of strawberry_plant_v2_root; "
            "mounted fruits and imported templates excluded"
        ),
        "bounds_m": {"min": _round_vector(lower), "max": _round_vector(upper)},
        "plant": plant,
        "attachments": attachments,
    }


def main() -> None:
    args = _argv()
    if len(args) != 4:
        raise SystemExit(
            "usage: blender --background --python export_gazebo_assets.py -- "
            "<fruit.blend> <plant.blend> <models-output-dir> <metadata.json>"
        )
    fruit_source, plant_source, output_root, metadata_path = map(Path, args)
    fruit_report = export_fruit(fruit_source, output_root)
    fruit_center = Vector(fruit_report["source_origin_m"])
    mount_point_model = Vector(fruit_report["mount_point_in_model_frame_m"])
    plant_report = export_plant(
        plant_source,
        output_root,
        fruit_center,
        mount_point_model,
    )
    report = {
        "schema_version": 1,
        "coordinate_contract": "metres, right-handed, Z-up, fruit model origin at body centre",
        "fruit": fruit_report,
        "plant": plant_report,
    }
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
