# Copyright 2026 Strawberry URP Team
# SPDX-License-Identifier: Apache-2.0

uint32 target_id
geometry_msgs/PoseStamped target_pose
---
bool feasible
bool collision
float32 planning_time_sec
float32 joint_travel_rad
string message
